import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";

const navItems: { label: string; page: string }[] = [
    { label: "Swap", page: "/" },
    { label: "Provide Liquidity", page: "/provide-liquidity" },
    { label: "Upgrade", page: "/upgrade" },
    { label: "Downgrade", page: "/downgrade" },
];

const Header = () => {
    const router = useRouter();

    return (
        <header className="flex flex-row justify-between h-32 w-full">
            <Head>
                <title>Aqueduct</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="p-1 border-solid border-teal-400 border-2">
                <h1 className="text-3xl font-bold">Aqueduct</h1>
            </div>
            <ul className="flex justify-between items-center h-9 w-100 p-3 m-2 bg-gray-800 rounded-2xl">
                {navItems.map(({ label, page }) => (
                    <li
                        key={label}
                        className={`rounded-2xl px-2 py-0.5 ${
                            router.asPath === page ? "bg-white text-black" : ""
                        }`}
                    >
                        <Link href={page}>
                            <a>{label}</a>
                        </Link>
                    </li>
                ))}
            </ul>
            <div className="p-1">Address: 0x123...</div>
        </header>
    );
};

export default Header;
