import type { NextPage } from "next";
import Head from "next/head";
import "tailwindcss/tailwind.css";

import Header from "../components/Header";
import Dashboard from "./Dashboard";

const Home: NextPage = () => {
    const tailwindGradient =
        "bg-gradient-to-t from-gray-700 via-gray-900 to-black";
    return (
        <div className={`w-full h-screen text-black ${tailwindGradient}`}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />

            <Dashboard />
        </div>
    );
};

export default Home;
