import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import FlowingBalance from "../components/FlowingBalance";
import Swap from "../components/Swap";

const Home: NextPage = () => {
    let balanceWei = "1000";
    let balanceTimestamp = 1000000;
    let flowRateWei = "1000";
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>Aqueduct</h1>

                <Swap />

                <FlowingBalance
                    balance={balanceWei} // call balanceOf function in AqueductToken
                    balanceTimestamp={balanceTimestamp} // unsure
                    flowRate={flowRateWei} // unsure
                />
            </main>
        </div>
    );
};

export default Home;
