import type { NextPage } from "next";
import Head from "next/head";
import "tailwindcss/tailwind.css";
import Header from "../components/Header";

const ProviderLiquidity: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main className="flex flex-col items-center h-full">
                Widget goes here
                {/* <Widget /> */}
            </main>
        </div>
    );
};

export default ProviderLiquidity;
